---
- name: "Send System Health to Telegram"
  hosts: localhost
  connection: local
  vars:
    tg_token: "{{ lookup('env', 'TG_TOKEN') }}"
    tg_chat_id: "{{ lookup('env', 'TG_CHAT_ID') }}"
  tasks:
    - name: "Check RAM Usage"
      ansible.builtin.shell: "free -m | awk 'NR==2{printf \"Memory Usage: %s/%sMB (%.2f%%)\\n\", $3,$2,$3*100/$2 }'"
      register: mem_usage
      changed_when: false

    - name: "Check Disk Usage"
      ansible.builtin.shell: "df -h / | awk 'NR==2 {print $5}'"
      register: disk_pcent
      changed_when: false

    - name: "Send message to Telegram"
      community.general.telegram:
        token: "{{ tg_token }}"
        api_args:
          chat_id: "{{ tg_chat_id }}"
          parse_mode: "Markdown"
          text: |
            *🚀 Отчет по системе (Bekbolat Labs)*
            ----------------------------------
            📊 *Память:* {{ mem_usage.stdout }}
            💾 *Диск:* Занято {{ disk_pcent.stdout }}
            🛡️ *Статус:* Проверка завершена успешно.
            ----------------------------------
