apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoPrivilegeEscalation
metadata:
  name: no-privilege-escalation
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
