apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: security-monitor-policy
  namespace: security-monitor
spec:
  podSelector:
    matchLabels:
      app: security-monitor
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: security-monitor
  egress:
  - to: []
