name: AI Security Gatekeeper

on:
  push:
    branches: [main, master]

jobs:
  security-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t security-monitor:latest .
          docker images | grep security-monitor

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d version

      - name: Create k3d cluster
        run: |
          k3d cluster create devsecops --wait
          kubectl get nodes

      - name: Import image to k3d
        run: |
          k3d image import security-monitor:latest -c devsecops

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan
        run: |
          trivy fs . --severity HIGH,CRITICAL --format json -o trivy-report.json
          cat trivy-report.json
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec on Terraform
        run: |
          tfsec terraform/

      - name: Install Python deps
        run: pip install requests python-dotenv

      - name: Debug Telegram vars
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python3 debug_ci.py

      - name: AI Security Decision
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python3 ai_security_advisor.py

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/namespace/namespace.yaml
          kubectl apply -f k8s/rbac/serviceaccount.yaml
          kubectl apply -f k8s/rbac/role.yaml
          kubectl apply -f k8s/rbac/rolebinding.yaml
          kubectl apply -f k8s/deployment/deployment.yaml
          kubectl apply -f k8s/service/service.yaml
          kubectl apply -f k8s/network-policy/network-policy.yaml
          kubectl get all -n security-monitor
