name: Ansible Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible and lint
        run: |
          pip install ansible ansible-lint

      - name: Install Ansible collections
        run: ansible-galaxy collection install community.general

      - name: Run Ansible Lint
        run: ansible-lint telegram_report.yml security_audit.yml
